exclude = [
    "__init__.py",
]

indent-width = 4
target-version = "py313"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]

select = [
  "A", "E", "F", "B",
  "S", "COM", "C4", "EXE", "ICN", "PIE", "PLR1714", "ARG",
  "PERF", "FURB", "PLE", "TRY", "W", "UP", "RUF", "SIM", "NPY",
  "EM", "RET", "PLR",
  "FIX", "TD",
  "D"
]
ignore = [
  "E501",     # line-too-long
  "D203",     # incorrect-blank-line-before-class
  "D213",     # multi-line-summary-second-line
  #"ANN", "Q000", "SLF001", "PLC0415", "N801", "I001", "CPY001"
]

preview = true

extend-select = ["DOC"]

extend-ignore = [
  "E201",  # whitespace-after-open-bracket
  "E221",  # multiple-spaces-before-operator
  "E222",  # multiple-spaces-after-operator
  "E225",  # missing-whitespace-around-operator
  "E241",  # multiple-spaces-after-comma
  "D413",  # missing-blank-line-after-last-section
]

[lint.per-file-ignores]
"vmol/__main__.py" = ["D"]
"examples/ex*.py"  = ["D"]
