name: release

on: # triggered by push tagged commits
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:

################################################################################################################################

  build_wheels:
    uses: ./.github/workflows/wheels.yml

################################################################################################################################

  build_exe:
    uses: ./.github/workflows/exe.yml


################################################################################################################################

  release:

    needs: [build_wheels, build_exe]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          path: ./wheelhouse

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./wheelhouse/**/*.whl
            ./wheelhouse/**/v
            ./wheelhouse/**/v.so

          body_path: .github/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

################################################################################################################################

  publish:
    needs: build_wheels
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts from this run
        uses: actions/download-artifact@v4
        with:
          pattern: vmol-wheels-*-${{ github.ref_name }}-${{ github.run_number }}
          merge-multiple: true
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          repository-url: https://upload.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}
